FROM mcr.microsoft.com/playwright@sha256:5b8f294aff9041b7191c34a4bab3ac270157a28774d4b0660e9743297b697e48

RUN apt-get update \
  && apt-get install -y --no-install-recommends libunbound8=1.19.2-1ubuntu3.8 \
  && rm -rf /var/lib/apt/lists/*

USER ubuntu
WORKDIR /app
